# Generated by Django 5.2.16 on 2026-09-08 19:42

import apps.news.models.configuration
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuration', '0005_trusted_source_prompt'),
        ('sources', '0005_alter_source_provider_sourcesubscription'),
        ('telegram', '0003_deliverytarget_feed'),
    ]

    operations = [
        migrations.CreateModel(
            name='XBudgetPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.DateField(unique=True)),
                ('limit', models.DecimalField(decimal_places=3, max_digits=8)),
                ('committed', models.DecimalField(decimal_places=3, default=0, max_digits=8)),
            ],
            options={
                'verbose_name': 'Бюджет X за неделю',
                'verbose_name_plural': 'Бюджеты X по неделям',
            },
        ),
        migrations.CreateModel(
            name='CollectionCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_hash', models.CharField(blank=True, max_length=64)),
                ('completed_until', models.DateTimeField(blank=True, null=True)),
                ('window_start', models.DateTimeField(blank=True, null=True)),
                ('window_end', models.DateTimeField(blank=True, null=True)),
                ('next_token', models.TextField(blank=True)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, verbose_name='Ошибка / пропуск')),
                ('source', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='sources.source')),
            ],
        ),
        migrations.CreateModel(
            name='NewsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(max_length=64, unique=True)),
                ('product', models.CharField(max_length=120, verbose_name='Продукт')),
                ('version', models.CharField(blank=True, max_length=180, verbose_name='Версия / функция')),
                ('event_type', models.CharField(max_length=32, verbose_name='Тип события')),
                ('score', models.PositiveSmallIntegerField(verbose_name='Оценка')),
                ('urgent', models.BooleanField(default=False, verbose_name='Срочная')),
                ('facts', models.JSONField(default=list)),
                ('first_seen_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('last_error', models.TextField(blank=True, verbose_name='Причина / ошибка')),
            ],
            options={
                'verbose_name': 'Новостное событие',
                'verbose_name_plural': 'Новостные события',
                'indexes': [models.Index(fields=['expires_at', 'score'], name='news_event_selection')],
            },
        ),
        migrations.CreateModel(
            name='NewsPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('preparing', 'Подготавливается'), ('ready', 'Подготовлена'), ('sending', 'Отправляется'), ('sent', 'Отправлена'), ('uncertain', 'Результат отправки неизвестен'), ('blocked', 'Заблокирована')], default='preparing', max_length=16, verbose_name='Статус')),
                ('title', models.CharField(blank=True, max_length=160, verbose_name='Заголовок')),
                ('text', models.TextField(blank=True, verbose_name='Текст')),
                ('rendered', models.TextField(blank=True)),
                ('payload_hash', models.CharField(blank=True, max_length=64)),
                ('prompt_versions', models.JSONField(blank=True, default=dict)),
                ('source_ids', models.JSONField(blank=True, default=list)),
                ('model', models.CharField(blank=True, max_length=200)),
                ('usage', models.JSONField(blank=True, default=dict)),
                ('slot_date', models.DateField(blank=True, null=True)),
                ('slot_minute', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('urgent', models.BooleanField(default=False)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('lease_until', models.DateTimeField(blank=True, null=True)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, verbose_name='Причина / ошибка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publications', to='news.newsevent')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='telegram.deliverytarget')),
            ],
            options={
                'verbose_name': 'Новостная публикация',
                'verbose_name_plural': 'Новостные публикации',
            },
        ),
        migrations.CreateModel(
            name='NewsDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_ids', models.JSONField(blank=True, default=list)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('resolution_note', models.TextField(blank=True, verbose_name='Результат проверки канала оператором')),
                ('publication', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='delivery', to='news.newspublication')),
            ],
            options={
                'verbose_name': 'Новостная доставка',
                'verbose_name_plural': 'Новостные доставки',
            },
        ),
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_key', models.CharField(max_length=100)),
                ('kind', models.CharField(max_length=20)),
                ('position', models.PositiveSmallIntegerField()),
                ('url', models.URLField(max_length=2000)),
                ('file', models.FileField(blank=True, upload_to='news')),
                ('checksum', models.CharField(blank=True, max_length=64)),
                ('size', models.PositiveBigIntegerField(default=0)),
                ('telegram_file_id', models.TextField(blank=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sources.sourcepost')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='news.newspublication')),
            ],
            options={
                'ordering': ('position', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='XApiUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(max_length=32)),
                ('reserved', models.DecimalField(decimal_places=3, max_digits=8)),
                ('charged_estimate', models.DecimalField(decimal_places=3, max_digits=8, null=True)),
                ('status', models.CharField(default='reserved', max_length=16)),
                ('resources', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sources.source')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='news.xbudgetperiod')),
            ],
            options={
                'verbose_name': 'Расход X',
                'verbose_name_plural': 'Расходы X',
            },
        ),
        migrations.CreateModel(
            name='NewsAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('running', 'Обрабатывается'), ('done', 'Завершён'), ('blocked', 'Заблокирован')], default='pending', max_length=16, verbose_name='Статус')),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('lease_until', models.DateTimeField(blank=True, null=True)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('model', models.CharField(blank=True, max_length=200)),
                ('prompt_version', models.PositiveIntegerField(default=0)),
                ('usage', models.JSONField(blank=True, default=dict)),
                ('last_error', models.TextField(blank=True, verbose_name='Причина / ошибка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='news_assessment', to='sources.sourcepost')),
            ],
            options={
                'verbose_name': 'Отбор новости',
                'verbose_name_plural': 'Отбор новостей',
                'indexes': [models.Index(fields=['status', 'next_attempt_at'], name='news_assessment_queue')],
            },
        ),
        migrations.CreateModel(
            name='NewsConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_enabled', models.BooleanField(default=False, verbose_name='Сбор новостей включён')),
                ('analysis_enabled', models.BooleanField(default=False, verbose_name='Анализ новостей включён')),
                ('publishing_enabled', models.BooleanField(default=False, verbose_name='Публикация новостей включена')),
                ('activated_at', models.DateTimeField(blank=True, null=True, verbose_name='Начало новостного потока')),
                ('timezone', models.CharField(default='Europe/Moscow', max_length=64, verbose_name='Часовой пояс публикаций')),
                ('windows', models.JSONField(default=apps.news.models.configuration.default_windows, verbose_name='Окна публикаций (минуты с начала суток)')),
                ('daily_limit', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='Максимум публикаций в сутки')),
                ('min_score', models.PositiveSmallIntegerField(default=70, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Минимальная оценка')),
                ('expiry_hours', models.PositiveSmallIntegerField(default=36, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(168)], verbose_name='Актуальность новости, часов')),
                ('weekly_x_limit', models.DecimalField(decimal_places=3, default=Decimal('3.000'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.100')), django.core.validators.MaxValueValidator(Decimal('3.000'))], verbose_name='Недельный бюджет новых X-запросов, USD')),
                ('llm_model', models.CharField(blank=True, max_length=200, verbose_name='Модель ИИ (пусто — системная)')),
                ('assessment_prompt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='news_assessment_configurations', to='configuration.prompttemplate', verbose_name='Промпт отбора')),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='telegram.deliverytarget', verbose_name='Новостной канал')),
                ('verification_prompt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='news_verification_configurations', to='configuration.prompttemplate', verbose_name='Промпт проверки')),
                ('writing_prompt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='news_writing_configurations', to='configuration.prompttemplate', verbose_name='Промпт редактора')),
            ],
            options={
                'verbose_name': 'Настройки новостей',
                'verbose_name_plural': 'Настройки новостей',
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='news_config_singleton')],
            },
        ),
        migrations.CreateModel(
            name='NewsDailyQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='telegram.deliverytarget')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('target', 'date'), name='news_target_day_unique')],
            },
        ),
        migrations.CreateModel(
            name='NewsEventEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facts', models.JSONField(default=list)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='news.newsevent')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sources.sourcepost')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('event', 'post'), name='news_event_post_unique')],
            },
        ),
        migrations.AddConstraint(
            model_name='newspublication',
            constraint=models.UniqueConstraint(fields=('event', 'target'), name='news_event_target_unique'),
        ),
        migrations.AddConstraint(
            model_name='mediaasset',
            constraint=models.UniqueConstraint(fields=('publication', 'media_key'), name='news_publication_media_unique'),
        ),
    ]
