# Generated by Django 5.2.16 on 2026-09-08 20:42

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_defaults'),
        ('sources', '0005_alter_source_provider_sourcesubscription'),
        ('telegram', '0003_deliverytarget_feed'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaasset',
            name='telegram_bot_identity',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='newspublication',
            name='media_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='newspublication',
            name='upload_media',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='InitialFill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('archive', 'Проверка архива'), ('collecting', 'Чтение истории'), ('assessing', 'Отбор'), ('publishing', 'Публикация'), ('completed', 'Завершено'), ('blocked', 'Остановлено')], default='archive', max_length=20, verbose_name='Статус')),
                ('window_start', models.DateTimeField(verbose_name='История с')),
                ('window_end', models.DateTimeField(verbose_name='История до')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(verbose_name='Завершить до')),
                ('committed', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=8, verbose_name='Расход и резерв X, USD')),
                ('lease_until', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, verbose_name='Причина / ошибка')),
                ('target', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='telegram.deliverytarget')),
            ],
            options={
                'verbose_name': 'Первичное наполнение',
                'verbose_name_plural': 'Первичное наполнение',
            },
        ),
        migrations.AddField(
            model_name='newspublication',
            name='initial_fill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='publications', to='news.initialfill'),
        ),
        migrations.AddField(
            model_name='xapiusage',
            name='initial_fill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='news.initialfill'),
        ),
        migrations.CreateModel(
            name='InitialFillAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='news.newsassessment')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='news.initialfill')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('run', 'assessment'), name='news_fill_assessment_unique')],
            },
        ),
        migrations.CreateModel(
            name='InitialFillSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_terms', models.CharField(blank=True, max_length=300)),
                ('next_token', models.TextField(blank=True)),
                ('done', models.BooleanField(default=False)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='news.initialfill')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sources.sourcesubscription')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('run', 'subscription'), name='news_fill_source_unique')],
            },
        ),
    ]
