# Generated by Django 5.2.16 on 2026-07-20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [("sources", "0002_initial_sources")]

    operations = [
        migrations.CreateModel(
            name="Analysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_relevant",
                    models.BooleanField(
                        blank=True,
                        help_text="Не задано, если анализ завершился ошибкой.",
                        null=True,
                        verbose_name="Релевантен",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("quota_reset", "Сброс квоты"),
                            ("quota_increase", "Повышение квоты"),
                            (
                                "quota_extension",
                                "Продление повышенной квоты",
                            ),
                        ],
                        max_length=32,
                        verbose_name="Тип события",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("openai", "OpenAI"), ("anthropic", "Anthropic")],
                        max_length=32,
                        verbose_name="Провайдер",
                    ),
                ),
                (
                    "product",
                    models.CharField(
                        choices=[("codex", "Codex"), ("claude_code", "Claude Code")],
                        max_length=32,
                        verbose_name="Продукт",
                    ),
                ),
                (
                    "title_ru",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Заголовок на русском",
                    ),
                ),
                (
                    "message_ru",
                    models.TextField(blank=True, verbose_name="Сообщение на русском"),
                ),
                ("model", models.CharField(max_length=200, verbose_name="Модель")),
                (
                    "prompt_version",
                    models.PositiveIntegerField(verbose_name="Версия промпта"),
                ),
                (
                    "raw_response",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Raw response"
                    ),
                ),
                ("error", models.TextField(blank=True, verbose_name="Ошибка анализа")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Изменён"),
                ),
                (
                    "source_post",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis",
                        to="sources.sourcepost",
                        verbose_name="Пост источника",
                    ),
                ),
            ],
            options={
                "verbose_name": "Анализ",
                "verbose_name_plural": "Анализы",
                "ordering": ("-created_at",),
            },
        )
    ]
