# Generated by Django 5.2.16 on 2026-09-08 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secrets', '0002_initial_secrets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encryptedsecret',
            name='code',
            field=models.CharField(choices=[('telegram_bot_token', 'Telegram Bot Token'), ('news_telegram_bot_token', 'Telegram Bot Token — новости'), ('llm_api_key', 'Ключ API ИИ-провайдера'), ('x_bearer_token', 'X Bearer Token'), ('proxy_url', 'URL прокси')], max_length=64, unique=True, verbose_name='Код'),
        ),
    ]
