# Generated by Django 5.2.16 on 2026-07-20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("openai", "OpenAI"), ("anthropic", "Anthropic")],
                        max_length=32,
                        verbose_name="Провайдер",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="Имя пользователя X",
                    ),
                ),
                (
                    "x_user_id",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="X User ID"
                    ),
                ),
                ("enabled", models.BooleanField(default=True, verbose_name="Активен")),
                (
                    "last_post_id",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        verbose_name="Последний Post ID",
                    ),
                ),
                (
                    "last_checked_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Последняя проверка",
                    ),
                ),
                (
                    "last_success_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Последний успех",
                    ),
                ),
                (
                    "last_error",
                    models.TextField(blank=True, verbose_name="Последняя ошибка"),
                ),
            ],
            options={
                "verbose_name": "Источник",
                "verbose_name_plural": "Источники",
                "ordering": ("provider", "username"),
            },
        ),
        migrations.CreateModel(
            name="SourcePost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="X Post ID"
                    ),
                ),
                ("text", models.TextField(verbose_name="Текст")),
                (
                    "normalized_text",
                    models.TextField(verbose_name="Нормализованный текст"),
                ),
                (
                    "source_url",
                    models.URLField(max_length=500, verbose_name="Ссылка на источник"),
                ),
                ("published_at", models.DateTimeField(verbose_name="Опубликован")),
                (
                    "received_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Получен"),
                ),
                ("raw_data", models.JSONField(verbose_name="Raw response")),
                (
                    "processing_status",
                    models.CharField(
                        choices=[
                            ("received", "Получен"),
                            ("queued", "Поставлен в очередь"),
                            ("analyzed_irrelevant", "Проанализирован: нерелевантен"),
                            ("analyzed_relevant", "Проанализирован: релевантен"),
                            ("failed", "Ошибка"),
                        ],
                        default="received",
                        max_length=32,
                        verbose_name="Статус обработки",
                    ),
                ),
                (
                    "last_error",
                    models.TextField(blank=True, verbose_name="Последняя ошибка"),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="posts",
                        to="sources.source",
                        verbose_name="Источник",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пост источника",
                "verbose_name_plural": "Посты источников",
                "ordering": ("-published_at", "-external_id"),
                "indexes": [
                    models.Index(
                        fields=["source", "published_at"],
                        name="sources_post_source_pub_idx",
                    ),
                    models.Index(
                        fields=["processing_status"],
                        name="sources_post_status_idx",
                    ),
                ],
            },
        ),
    ]
