# Generated by Django 5.2.16 on 2026-09-08 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0004_trusted_codex_sources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='provider',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('cursor', 'Cursor'), ('google', 'Google')], max_length=32, verbose_name='Провайдер'),
        ),
        migrations.CreateModel(
            name='SourceSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed', models.CharField(choices=[('quota', 'Квоты'), ('news', 'Новости')], max_length=16, verbose_name='Направление')),
                ('enabled', models.BooleanField(default=False, verbose_name='Активна')),
                ('priority', models.BooleanField(default=False, verbose_name='Приоритетный источник')),
                ('query_terms', models.CharField(blank=True, max_length=300, verbose_name='Тематический фильтр X')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='sources.source')),
            ],
            options={
                'verbose_name': 'Подписка на источник',
                'verbose_name_plural': 'Подписки на источники',
                'constraints': [models.UniqueConstraint(fields=('source', 'feed'), name='source_feed_unique')],
            },
        ),
    ]
