# Generated by Django 5.2.16 on 2026-09-29 09:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('telegram', '0004_delivery_message_entities_delivery_rendered_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Текст рекламы')),
                ('link_label', models.CharField(max_length=200, verbose_name='Текст ссылки')),
                ('url', models.URLField(max_length=2000, verbose_name='URL')),
                ('total_posts', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество постов')),
                ('enabled', models.BooleanField(default=False, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='telegram.deliverytarget', verbose_name='Канал')),
            ],
            options={
                'verbose_name': 'Рекламная кампания',
                'verbose_name_plural': 'Рекламные кампании',
                'ordering': ('-created_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('reserved', 'Зарезервировано'), ('sending', 'Отправляется'), ('uncertain', 'Требуется проверка канала'), ('sent', 'Опубликовано'), ('released', 'Не опубликовано')], default='reserved', max_length=16, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Зарезервировано')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Опубликовано')),
                ('resolution_note', models.TextField(blank=True, verbose_name='Результат проверки канала')),
                ('telegram_message_id', models.CharField(blank=True, max_length=64, verbose_name='Telegram message ID найденного поста')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='placements', to='advertising.campaign', verbose_name='Кампания')),
                ('delivery', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='advertising', to='telegram.delivery', verbose_name='Доставка')),
            ],
            options={
                'verbose_name': 'Рекламное размещение',
                'verbose_name_plural': 'Рекламные размещения',
                'ordering': ('-created_at', '-pk'),
            },
        ),
        migrations.AddConstraint(
            model_name='campaign',
            constraint=models.UniqueConstraint(condition=models.Q(('enabled', True)), fields=('target',), name='advertising_one_active_target'),
        ),
        migrations.AddConstraint(
            model_name='campaign',
            constraint=models.CheckConstraint(condition=models.Q(('total_posts__gte', 1)), name='advertising_positive_total'),
        ),
    ]
