# Generated by Django 5.2.16 on 2026-09-29 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='body',
            field=models.TextField(blank=True, verbose_name='Текст рекомендации'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='link_label',
            field=models.CharField(blank=True, max_length=200, verbose_name='Текст ссылки'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='message',
            field=models.TextField(blank=True, verbose_name='Текст рекламы'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='url',
            field=models.URLField(blank=True, max_length=2000, verbose_name='URL'),
        ),
    ]
