# Generated by Django 5.2.16 on 2026-07-20 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("analysis", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryTarget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[("channel", "Канал"), ("private_chat", "Личный чат")],
                        max_length=32,
                        verbose_name="Тип получателя",
                    ),
                ),
                (
                    "telegram_chat_id",
                    models.CharField(
                        max_length=128,
                        unique=True,
                        verbose_name="Telegram chat ID или @username",
                    ),
                ),
                ("enabled", models.BooleanField(default=True, verbose_name="Активен")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Изменён"),
                ),
            ],
            options={
                "verbose_name": "Получатель Telegram",
                "verbose_name_plural": "Получатели Telegram",
                "ordering": ("target_type", "telegram_chat_id"),
                "indexes": [
                    models.Index(
                        fields=["enabled", "target_type"],
                        name="telegram_target_enabled_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Delivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает"),
                            ("sent", "Отправлено"),
                            ("failed", "Ошибка"),
                        ],
                        default="pending",
                        max_length=16,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "telegram_message_id",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Telegram message ID"
                    ),
                ),
                (
                    "attempts",
                    models.PositiveIntegerField(default=0, verbose_name="Попыток"),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Отправлено"
                    ),
                ),
                (
                    "last_error",
                    models.TextField(blank=True, verbose_name="Последняя ошибка"),
                ),
                (
                    "analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deliveries",
                        to="analysis.analysis",
                        verbose_name="Анализ",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deliveries",
                        to="telegram.deliverytarget",
                        verbose_name="Получатель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Доставка Telegram",
                "verbose_name_plural": "Доставки Telegram",
                "ordering": ("-sent_at", "-pk"),
                "indexes": [
                    models.Index(fields=["status"], name="telegram_delivery_status_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("analysis", "target"),
                        name="telegram_delivery_analysis_target_uniq",
                    )
                ],
            },
        ),
    ]
