# Generated by Django 5.2.16 on 2026-09-08 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0002_delivery_recovery_timestamps'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverytarget',
            name='feed',
            field=models.CharField(choices=[('quota', 'Квоты'), ('news', 'Новости')], default='quota', max_length=16, verbose_name='Направление'),
        ),
    ]
