# Generated by Django 5.2.16 on 2026-09-29 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0003_deliverytarget_feed'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='message_entities',
            field=models.JSONField(blank=True, default=list, verbose_name='Форматирование ссылок'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='rendered_text',
            field=models.TextField(blank=True, verbose_name='Зафиксированный текст поста'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('sent', 'Отправлено'), ('failed', 'Ошибка'), ('uncertain', 'Требуется проверка канала')], default='pending', max_length=16, verbose_name='Статус'),
        ),
    ]
